% Writes LaTeX \newcommand definitions to a fragment file (regenerated wholesale).
% names: cellstr of macro names (letters only); values: cellstr/numeric cell.
%
function write_tex_macros(fname,names,values)

[p,~,~] = fileparts(fname);
if ~isempty(p) && ~exist(p,'dir')
    mkdir(p)
end
fid = fopen(fname,'w');
fprintf(fid,'%% Auto-generated by the wind-wave figure pipeline; do not edit by hand\n');
for i = 1:numel(names)
    v = values{i};
    if ~ischar(v) && ~isstring(v)
        v = num2str(v);
    end
    fprintf(fid,'\\newcommand{\\%s}{%s}\n',names{i},char(v));
end
fclose(fid);
