% Writes LaTeX \newcommand definitions to a fragment file (regenerated wholesale)
%
% Inputs:
% * fname  - fragment file, created along with its folder if absent
% * names  - cellstr of macro names (letters only)
% * values - cellstr or numeric cell, one per name
%
% Warns on a non-finite value, which would otherwise reach the manuscript
%
% Nathan Laxague 2026
%
function write_tex_macros(fname,names,values)

[p,~,~] = fileparts(fname);
if ~isempty(p) && ~exist(p,'dir')
    mkdir(p)
end

fid = fopen(fname,'w');

fprintf(fid,'%% Auto-generated by the wind-wave figure pipeline; do not edit by hand\n');

for i = 1:numel(names)

    v = values{i};
    if ~ischar(v) && ~isstring(v)
        v = num2str(v);
    end

    if any(strcmpi(strtrim(char(v)),{'NaN','-NaN','Inf','-Inf'}))
        warning('write_tex_macros:nonFinite', ...
            '%s: macro \\%s is %s; the manuscript will print it verbatim', ...
            fname,names{i},strtrim(char(v)))
    end

    fprintf(fid,'\\newcommand{\\%s}{%s}\n',names{i},char(v));

end

fclose(fid);
